version: '3'
services:
      mysql-standalone:
        image: 'mysql:8.0'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=my_db
        ports:
          - "3307:3306"
        volumes:
          - mysql-data:/var/lib/mysql
      springboot-docker-container:
        image: words-processing-app
        ports:
          - "8080:8080"
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql//mysql-standalone3306/gui/getAll
          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "root"
        build:
           context: "./"
           dockerfile: "DockerFile"
        depends_on:
          - mysql-standalone
volumes:
  mysql-data:
